config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  get 'homes/about' => 'homes#about', as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  
  belongs_to :user
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

    def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpeg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      about_path
    end

    def after_sign_out_path_for(resource)
      about_path
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body, :image, :caption)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[id])
    @books = @user.books
    @book = Book.new
  end
  
  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfuly."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def index
    @users = User.all
    @books = Book.all
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <p><h2>User info</h2></p>
        
        <table class="table">
          <tbody>
            <tr>
              <p><%= image_tag user.get_profile_image(100,100) %></p>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        
        <%= link_to edit_user_path(user), class:'btn btn-light btn-outline-secondary btn-block' do %>
          <i class="fa-solid fa-user-cog"></i>
        <% end %>

        <p><h1>New book</h1></p>
        <%= form_with model: book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
  
        <p>Opinion</p>
        <%=f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model: @book, url: update_list_path(@book.id), method: :patch do |f| %>

          <h5>Title</h5>
          <%= f.text_field :title %>

          <h5>Opinion</h5>
          <%= f.text_area :body %>

          <%= f.submit 'Update Book' %>

        <% end %>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<%= render 'left', book: @book, user: @user %>

  <div class="col-md-8 offset-md-1">
    <p><h1>Books</h1></p>
    
    <table class="table">
      <tbody>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        
        <p><h2>User info</h2></p>
        
        <table class="table">
          <tbody>
            <tr>
              <p><%= image_tag @user.get_profile_image(100,100) %></p>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        
        <%= link_to edit_user_path(@user), class:'btn btn-light btn-outline-secondary btn-block' do %>
          <i class="fa-solid fa-user-cog"></i>
        <% end %>

        <p><h1>New book</h1></p>
        <%= form_with model: @booknew do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
  
        <p>Opinion</p>
        <%=f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        
      <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <% @book.user %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %></td>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            <td><%=@book.title%></td>
            <td><%=@book.body%></td>
        </tr>
      
    </table>
  </div>
</main>

app/views/homes/about.html.erb
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
              welcome to
              <i class="fas fa-book" aria-hidden="true"></i>
              <strong>Bookers</strong>
              !!
            </h1>
          </div>
        <div>
      </div>
    </main>

app/views/homes/top.html.erb
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
              welcome to
              <i class="fas fa-book" aria-hidden="true"></i>
              <strong>Bookers</strong>
              !!
            </h1>
            <p>
              in
              <i class="fas fa-book" aria-hidden="true"></i>
              <strong>Bookers</strong>
              ,
            </p>
            <p>
              you can share and exchange your opinions , inpressions , and emotions
            </p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
              <div class="row">
                <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
              </div>
              <div class="row">
                <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3d8bebdbd6.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="https://2a55bfd4e3f946fe8cf1b0c80da7c0ae.vfs.cloud9.ap-northeast-1.amazonaws.com/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Home', user_path(current_user.id), class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'Users', users_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'Books', books_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Home', root_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'About', about_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'Sign up', new_user_registration_path, class: "nav-link text-light" %>
                </li>
                <li>
                  <%= link_to 'Log in', user_session_path, class: "nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
<%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>